# Collaborative Filtering on the small dataset

In [15]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
import sqlalchemy as sql

In [2]:
df = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')

In [3]:
df = pd.merge(df, movies, on='movieId')
df = df.drop('timestamp', axis =1)

In [4]:
df

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...
100831,610,160341,2.5,Bloodmoon (1997),Action|Thriller
100832,610,160527,4.5,Sympathy for the Underdog (1971),Action|Crime|Drama
100833,610,160836,3.0,Hazard (2005),Action|Drama|Thriller
100834,610,163937,3.5,Blair Witch (2016),Horror|Thriller
100835,610,163981,3.5,31 (2016),Horror

In [7]:
df2 = df.pivot(index='userId', columns='movieId', values='rating')

In [8]:
df2

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,2.5,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_filled = df2.fillna(3.5)

In [14]:
cosin_matrix = cosine_similarity(df_filled)

In [30]:
pd.DataFrame(cosin_matrix)

,0,1,2,3,4,5,6,7,8,9,...,600,601,602,603,604,605,606,607,608,609
0,1.000000,0.998594,0.997722,0.997263,0.998555,0.997772,0.997613,0.998548,0.998426,0.997766,...,0.998358,0.998224,0.993417,0.998441,0.997930,0.996308,0.998063,0.994143,0.998641,0.995013
1,0.998594,1.000000,0.999017,0.998322,0.999721,0.998950,0.998714,0.999710,0.999583,0.999056,...,0.999488,0.999349,0.994679,0.999669,0.999203,0.997391,0.999105,0.995379,0.999859,0.995878
2,0.997722,0.999017,1.000000,0.997525,0.998899,0.998181,0.997950,0.998896,0.998800,0.998282,...,0.998627,0.998547,0.993966,0.998887,0.998419,0.996482,0.998313,0.994575,0.999078,0.995075
3,0.997263,0.998322,0.997525,1.000000,0.998238,0.997531,0.997436,0.998258,0.998121,0.997725,...,0.997930,0.998023,0.993414,0.998198,0.997815,0.996028,0.997700,0.993796,0.998398,0.994368
4,0.998555,0.999721,0.998899,0.998238,1.000000,0.998887,0.998662,0.999642,0.999503,0.998955,...,0.999396,0.999307,0.994649,0.999595,0.999087,0.997346,0.999055,0.995270,0.999793,0.995729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,0.996308,0.997391,0.996482,0.996028,0.997346,0.996518,0.996419,0.997333,0.997225,0.996503,...,0.997307,0.996984,0.992991,0.997341,0.996839,1.000000,0.996742,0.993409,0.997465,0.994004
606,0.998063,0.999105,0.998313,0.997700,0.999055,0.998373,0.998145,0.999079,0.998890,0.998323,...,0.998871,0.998746,0.994166,0.998992,0.998483,0.996742,1.000000,0.994779,0.999166,0.995299
607,0.994143,0.995379,0.994575,0.993796,0.995270,0.994578,0.994299,0.995393,0.995205,0.994435,...,0.995247,0.995085,0.990479,0.995245,0.994739,0.993409,0.994779,1.000000,0.995479,0.991868
608,0.998641,0.999859,0.999078,0.998398,0.999793,0.999020,0.998792,0.999784,0.999644,0.999115,...,0.999522,0.999427,0.994765,0.999739,0.999251,0.997465,0.999166,0.995479,1.000000,0.995842
609,0.995013,0.995878,0.995075,0.994368,0.995729,0.995000,0.994958,0.995760,0.995701,0.994923,...,0.995943,0.995454,0.991208,0.995702,0.995406,0.994004,0.995299,0.991868,0.995842,1.000000

# With this matrix, we can create recommendations:

- create a list of unseen movies of the active user
- for each unseen movie: check who has rated it and who is closest to the active user
- also for each movie: predict the rating based on the (weighted) average ratings of the neighbours
- collect all unseen movies with the predicted ratings
- sort and select top recommendations (best-rated per prediction) 


(This can all be done with merely writing for-loops and comparing values.)

## create a list of unseen movies of the active user

In [16]:
HOST = '34.89.195.148'
USERNAME = 'postgres'
PORT = '5432'
DB = 'moviedb'
PASSWORD = 'postgres'
engine = sql.create_engine(f'postgres://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DB}')

query = sql.text(" select * from ratings WHERE userId = 1")
results = engine.execute(query)
results = pd.DataFrame(results)
results.columns = ['userId', 'movieId', 'ratings', 'timestamp']
results = results.drop('timestamp', axis = 1)

In [19]:
#preparing the movies df
df = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')
unique = pd.DataFrame(df.movieId.unique())
unique.columns = ['movieId'] 
movies = movies.merge(unique, how='right')
movies  = movies.drop('genres', axis = 1)

In [26]:
unseen = results.merge(movies, how = 'right')
unseen = unseen[unseen['ratings'].isna()]

In [27]:
unseen_movie = list(unseen['movieId'])

In [29]:
unseen_movie

[318,
 1704,
 6874,
 8798,
 46970,
 48516,
 58559,
 60756,
 68157,
 71535,
 74458,
 77455,
 79132,
 80489,
 80906,
 86345,
 89774,
 91529,
 91658,
 99114,
 106782,
 109487,
 112552,
 114060,
 115713,
 122882,
 131724,
 31,
 647,
 688,
 720,
 849,
 914,
 1093,
 1124,
 1263,
 1272,
 1302,
 1371,
 2080,
 2288,
 2424,
 2851,
 3024,
 3210,
 3949,
 4518,
 5048,
 5181,
 5746,
 5764,
 5919,
 6238,
 6835,
 7899,
 7991,
 26409,
 70946,
 72378,
 21,
 32,
 45,
 52,
 58,
 106,
 125,
 126,
 162,
 171,
 176,
 190,
 215,
 222,
 232,
 247,
 265,
 319,
 342,
 345,
 348,
 351,
 357,
 368,
 417,
 450,
 475,
 492,
 509,
 538,
 539,
 588,
 595,
 599,
 708,
 759,
 800,
 892,
 898,
 899,
 902,
 904,
 908,
 910,
 912,
 920,
 930,
 937,
 1046,
 1057,
 1077,
 1079,
 1084,
 1086,
 1094,
 1103,
 1179,
 1183,
 1188,
 1199,
 1203,
 1211,
 1225,
 1250,
 1259,
 1266,
 1279,
 1283,
 1288,
 1304,
 1391,
 1449,
 1466,
 1597,
 1641,
 1719,
 1733,
 1734,
 1834,
 1860,
 1883,
 1885,
 1892,
 1895,
 1907,
 1914,
 1916,
 1923,
 1947,
 1966,
 1968,
 2019,
 2076,
 2109,
 2145,
 2150,
 2186,
 2203,
 2204,
 2282,
 2324,
 2336,
 2351,
 2359,
 2390,
 2467,
 2583,
 2599,
 2683,
 2712,
 2762,
 2763,
 2770,
 2791,
 2843,
 2874,
 2921,
 2926,
 2973,
 3044,
 3060,
 3079,
 3083,
 3160,
 3175,
 3204,
 3255,
 3317,
 3358,
 3365,
 3408,
 3481,
 3508,
 3538,
 3591,
 3788,
 3851,
 3897,
 3911,
 3967,
 3996,
 4002,
 4014,
 4020,
 4021,
 4027,
 4029,
 4033,
 4034,
 4074,
 4121,
 4144,
 4166,
 4226,
 4239,
 4246,
 4252,
 4260,
 4273,
 4308,
 4347,
 4381,
 4641,
 4741,
 4765,
 4881,
 4896,
 4902,
 4967,
 34,
 36,
 39,
 150,
 153,
 253,
 261,
 266,
 290,
 300,
 344,
 364,
 380,
 410,
 474,
 515,
 531,
 534,
 589,
 594,
 597,
 2,
 4,
 5,
 7,
 8,
 10,
 11,
 13,
 15,
 16,
 17,
 19,
 22,
 24,
 25,
 26,
 27,
 41,
 43,
 46,
 54,
 60,
 61,
 62,
 65,
 66,
 76,
 79,
 86,
 87,
 88,
 89,
 92,
 93,
 95,
 100,
 102,
 104,
 105,
 112,
 113,
 135,
 140,
 141,
 145,
 146,
 158,
 159,
 160,
 161,
 165,
 168,
 170,
 174,
 177,
 179,
 180,
 181,
 185,
 186,
 189,
 191,
 195,
 196,
 201,
 204,
 205,
 207,
 208,
 209,
 210,
 212,
 217,
 218,
 219,
 224,
 225,
 230,
 234,
 236,
 237,
 239,
 240,
 243,
 248,
 250,
 251,
 252,
 254,
 256,
 257,
 258,
 262,
 267,
 270,
 271,
 273,
 274,
 276,
 277,
 279,
 281,
 282,
 288,
 289,
 291,
 292,
 293,
 302,
 303,
 304,
 310,
 312,
 313,
 314,
 315,
 317,
 327,
 329,
 330,
 332,
 336,
 337,
 339,
 340,
 343,
 347,
 350,
 352,
 353,
 354,
 355,
 358,
 359,
 360,
 361,
 366,
 370,
 371,
 374,
 377,
 378,
 381,
 382,
 383,
 405,
 412,
 415,
 416,
 419,
 426,
 432,
 434,
 435,
 437,
 440,
 445,
 454,
 455,
 458,
 460,
 466,
 468,
 469,
 472,
 477,
 485,
 489,
 490,
 491,
 493,
 494,
 497,
 502,
 505,
 508,
 510,
 516,
 520,
 524,
 532,
 536,
 537,
 540,
 542,
 546,
 548,
 569,
 575,
 587,
 606,
 609,
 616,
 628,
 631,
 637,
 640,
 662,
 667,
 694,
 697,
 700,
 704,
 709,
 710,
 711,
 719,
 747,
 762,
 765,
 775,
 783,
 795,
 799,
 801,
 802,
 818,
 830,
 835,
 837,
 838,
 839,
 842,
 848,
 852,
 867,
 880,
 881,
 888,
 891,
 979,
 981,
 986,
 991,
 996,
 999,
 1004,
 1006,
 1061,
 1064,
 1082,
 750,
 924,
 1101,
 1246,
 1584,
 1610,
 1682,
 1784,
 1917,
 2671,
 2688,
 2701,
 2717,
 3114,
 3354,
 3623,
 3869,
 3916,
 3977,
 3994,
 4018,
 4223,
 4306,
 4310,
 4370,
 4643,
 4700,
 4844,
 4874,
 4886,
 4963,
 4993,
 4995,
 5218,
 5349,
 5378,
 5445,
 5459,
 5464,
 5502,
 5618,
 5816,
 5952,
 5989,
 5991,
 6333,
 6365,
 6534,
 6539,
 6863,
 6934,
 7143,
 7153,
 7155,
 7445,
 8207,
 8360,
 8368,
 8373,
 8528,
 8636,
 8665,
 8666,
 8783,
 8808,
 8865,
 8870,
 8907,
 8908,
 8949,
 8957,
 8958,
 8961,
 8965,
 8970,
 8972,
 8984,
 27741,
 30812,
 30816,
 31878,
 32029,
 32031,
 32296,
 32587,
 33162,
 33493,
 33794,
 33836,
 34048,
 34319,
 37741,
 38388,
 42002,
 45499,
 45517,
 45668,
 45730,
 46530,
 48783,
 48997,
 49272,
 49278,
 49286,
 49824,
 586,
 187,
 627,
 922,
 1037,
 1095,
 1674,
 1987,
 2011,
 2023,
 2300,
 2877,
 2901,
 3173,
 3328,
 3735,
 4131,
 4558,
 5447,
 5451,
 5481,
 5507,
 5841,
 5843,
 5872,
 5890,
 5891,
 5893,
 5902,
 5956,
 5962,
 5965,
 5988,
 6001,
 6044,
 1028,
 1088,
 1247,
 1307,
 3882,
 4447,
 5066,
 5377,
 5620,
 5943,
 5957,
 6155,
 6266,
 6377,
 6535,
 6942,
 7149,
 7151,
 7154,
 7169,
 7293,
 7375,
 7451,
 7458,
 8529,
 8533,
 8869,
 8969,
 30749,
 31433,
 31685,
 33145,
 33679,
 40629,
 40819,
 41285,
 47099,
 51662,
 51705,
 51834,
 54286,
 56367,
 56949,
 58047,
 59333,
 59421,
 60397,
 60950,
 61250,
 63113,
 63992,
 64969,
 66203,
 68954,
 69406,
 69844,
 70183,
 70293,
 71579,
 72011,
 72330,
 72407,
 72720,
 72737,
 72998,
 73017,
 74450,
 77841,
 78772,
 79091,
 80549,
 81784,
 81845,
 81847,
 82167,
 82499,
 84374,
 86548,
 87222,
 88163,
 88810,
 91104,
 92259,
 94070,
 95167,
 95449,
 95510,
 95543,
 96079,
 97024,
 97938,
 98203,
 103335,
 103339,
 104374,
 105211,
 106489,
 106696,
 107141,
 109374,
 109853,
 112006,
 113275,
 113394,
 119145,
 129428,
 136020,
 137595,
 140110,
 44,
 376,
 511,
 529,
 1100,
 1358,
 1370,
 1385,
 1438,
 1518,
 1586,
 1604,
 1608,
 1616,
 1687,
 1693,
 1721,
 1840,
 1882,
 1918,
 2002,
 2027,
 1357,
 1405,
 1876,
 2072,
 2100,
 2421,
 2485,
 2572,
 2581,
 2694,
 3668,
 305,
 1173,
 1590,
 1619,
 1639,
 2541,
 3300,
 3409,
 3513,
 3624,
 3717,
 3753,
 3798,
 3827,
 3863,
 3893,
 3952,
 4011,
 4148,
 193,
 448,
 784,
 172,
 858,
 1200,
 1347,
 1527,
 1653,
 1909,
 2001,
 2081,
 2085,
 2278,
 3156,
 3499,
 3510,
 3535,
 3555,
 4022,
 4720,
 5971,
 6502,
 7254,
 7438,
 8644,
 48304,
 48774,
 48780,
 50872,
 56174,
 59315,
 60069,
 63859,
 64614,
 68237,
 69757,
 70286,
 71057,
 71264,
 84152,
 84954,
 85414,
 89745,
 91500,
 94864,
 96610,
 101864,
 103249,
 104841,
 105504,
 110102,
 111759,
 112556,
 112852,
 115149,
 120466,
 122886,
 122904,
 122922,
 122924,
 134130,
 134853,
 143385,
 152077,
 152081,
 158872,
 160980,
 166528,
 166635,
 111,
 541,
 678,
 745,
 913,
 1147,
 1148,
 1186,
 1193,
 1201,
 1207,
 1223,
 1230,
 1252,
 1260,
 1261,
 1267,
 1276,
 1281,
 1299,
 1680,
 2490,
 2707,
 2723,
 3000,
 3022,
 3108,
 3174,
 3429,
 3683,
 3741,
 4878,
 4973,
 5782,
 6350,
 7099,
 7361,
 27611,
 27773,
 48394,
 78499,
 1036,
 1209,
 1221,
 1228,
 1234,
 1375,
 2194,
 3039,
 3263,
 3435,
 3681,
 4571,
 6016,
 6870,
 7482,
 31658,
 64839,
 68358,
 80463,
 81932,
 82459,
 431,
 442,
 555,
 653,
 778,
 1020,
 1059,
 1212,
 1227,
 1245,
 1356,
 1374,
 1544,
 1729,
 1924,
 1961,
 2184,
 2409,
 2410,
 2411,
 2412,
 2420,
 2422,
 2706,
 2918,
 2951,
 2953,
 3081,
 3257,
 3275,
 3462,
 3751,
 3785,
 3896,
 4007,
 4262,
 4327,
 4383,
 4728,
 4816,
 5008,
 5120,
 5266,
 5418,
 5574,
 5608,
 5669,
 5679,
 5903,
 5944,
 5995,
 6287,
 6300,
 6373,
 6378,
 6440,
 6548,
 6709,
 6787,
 6807,
 6888,
 7018,
 7147,
 7317,
 7318,
 7323,
 7373,
 7753,
 7843,
 8117,
 8361,
 8641,
 8784,
 8917,
 8950,
 26444,
 26614,
 ...]

## for each unseen movie: check who has rated it and who is closest to the active user

In [ ]:
#check who has rated the movie 318 and put them in a list
# from this list, check who is most similar, 
# take 5 similar users, check how they rqted the movie 
# create an average of these rtings and that's the prediction for the movieid 318